/* RUN -> SE CREARÁ PROCEDIMIENTO (REVISAR CARPETA PROCEDIMIENTOS) */
/* RUN PROCEDIMIENTO -> AGREGAR PARÁMETROS -> ACEPTAR -> SE CREARÁ REGISTRO EN LA TABLA CURSO */
CREATE OR REPLACE PROCEDURE INSERT_PRUEBA (ID_CURSO IN NUMBER, NOMBRE IN VARCHAR2, CANTHORAS IN NUMBER, CATEGORIA_IDCATEGORIA IN NUMBER)
IS
BEGIN
    INSERT INTO CURSO(ID_CURSO, NOMBRE, CANTHORAS, CATEGORIA_IDCATEGORIA) VALUES(ID_CURSO, NOMBRE, CANTHORAS, CATEGORIA_IDCATEGORIA);
    DBMS_OUTPUT.PUT_LINE('REGISTRO EXITOSO');
END;
/